services:
  mysql:
    image: mysql:8.0
    container_name: commerse_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commerse_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: CommersePassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
